.PHONY: integration-test

GENERATED_PROJECT := /tmp/search-starter-app-integration-test

## Generate a project from the template and run integration tests
integration-test:
	rm -rf $(GENERATED_PROJECT)
	copier copy --defaults --UNSAFE --vcs-ref=HEAD . $(GENERATED_PROJECT)
	$(MAKE) _test-uv-lock-generated
	$(MAKE) _test-vespa-app-import
	$(MAKE) _test-ingest-help
	$(MAKE) _test-search-help
	$(MAKE) _test-wheel-contents
	@echo ""
	@echo "All integration tests passed."

_test-uv-lock-generated:
	@echo "--- test: make installdeps generates uv.lock"
	@cd $(GENERATED_PROJECT) && make installdeps > /dev/null 2>&1
	@test -f $(GENERATED_PROJECT)/uv.lock \
		&& echo "OK: uv.lock generated" \
		|| (echo "FAIL: uv.lock was not generated by make installdeps" && exit 1)

_test-vespa-app-import:
	@echo "--- test: vespa_app module imports"
	cd $(GENERATED_PROJECT) && uv run python -c \
		"from vespa_app import app; assert app is not None; print('OK: vespa_app imported')"

_test-ingest-help:
	@echo "--- test: entrypoints.ingest --help"
	cd $(GENERATED_PROJECT) && uv run python -m entrypoints.ingest --help > /dev/null 2>&1 \
		&& echo "OK: ingest --help works" \
		|| (echo "FAIL: ingest --help failed" && exit 1)

_test-search-help:
	@echo "--- test: entrypoints.search --help"
	cd $(GENERATED_PROJECT) && uv run python -m entrypoints.search --help > /dev/null 2>&1 \
		&& echo "OK: search --help works" \
		|| (echo "FAIL: search --help failed" && exit 1)

_test-wheel-contents:
	@echo "--- test: built wheel ships entrypoints and vespa_app"
	cd $(GENERATED_PROJECT) && rm -rf dist && uv build --wheel > /dev/null
	cd $(GENERATED_PROJECT) && unzip -l dist/*.whl \
		| grep -q "entrypoints/ingest.py" \
		&& unzip -l dist/*.whl | grep -q "vespa_app/__init__.py" \
		&& echo "OK: wheel contains entrypoints and vespa_app" \
		|| (echo "FAIL: wheel is missing required packages" && exit 1)
