.PHONY: integration-test integration-test-postgres _integration-test-body

GENERATED_PROJECT := /tmp/search-starter-app-integration-test

# Backend under test (vespa | postgres). Override on the command line, e.g.
#   make integration-test BACKEND=postgres POSTGRES_PLUGIN_PATH=../dashboard/search/toolkit/plugins/postgres
BACKEND ?= vespa

# Local checkout of the (currently unpublished) postgres plugin. Required for
# BACKEND=postgres so uv can resolve it via the generated [tool.uv.sources] shim.
POSTGRES_PLUGIN_PATH ?=

# Extra copier data passed to the postgres run.
ifeq ($(BACKEND),postgres)
COPIER_DATA := --data backend=postgres --data postgres_plugin_path=$(POSTGRES_PLUGIN_PATH)
else
COPIER_DATA := --data backend=vespa
endif

## Generate a project from the template and run integration tests (default: vespa)
integration-test: _integration-test-body

## Generate + test the postgres variant. Requires POSTGRES_PLUGIN_PATH.
integration-test-postgres:
	@test -n "$(POSTGRES_PLUGIN_PATH)" \
		|| (echo "FAIL: set POSTGRES_PLUGIN_PATH to a local postgres plugin checkout" && exit 1)
	$(MAKE) _integration-test-body BACKEND=postgres POSTGRES_PLUGIN_PATH=$(POSTGRES_PLUGIN_PATH)

_integration-test-body:
	@echo "=== integration-test (backend=$(BACKEND)) ==="
	rm -rf $(GENERATED_PROJECT)
	copier copy --defaults --vcs-ref=HEAD $(COPIER_DATA) . $(GENERATED_PROJECT)
	$(MAKE) _test-uv-lock-generated
	$(MAKE) _test-search-app-import
	$(MAKE) _test-ingest-help
	$(MAKE) _test-search-help
	$(MAKE) _test-wheel-contents
	@echo ""
	@echo "All integration tests passed (backend=$(BACKEND))."

_test-uv-lock-generated:
	@echo "--- test: make installdeps generates uv.lock"
	@cd $(GENERATED_PROJECT) && make installdeps > /dev/null 2>&1
	@test -f $(GENERATED_PROJECT)/uv.lock \
		&& echo "OK: uv.lock generated" \
		|| (echo "FAIL: uv.lock was not generated by make installdeps" && exit 1)

_test-search-app-import:
	@echo "--- test: search_app module imports"
	cd $(GENERATED_PROJECT) && uv run python -c \
		"from search_app import app, get_index; assert app is not None and get_index is not None; print('OK: search_app imported')"

_test-ingest-help:
	@echo "--- test: entrypoints.ingest --help"
	cd $(GENERATED_PROJECT) && uv run python -m entrypoints.ingest --help > /dev/null 2>&1 \
		&& echo "OK: ingest --help works" \
		|| (echo "FAIL: ingest --help failed" && exit 1)

_test-search-help:
	@echo "--- test: entrypoints.search --help"
	cd $(GENERATED_PROJECT) && uv run python -m entrypoints.search --help > /dev/null 2>&1 \
		&& echo "OK: search --help works" \
		|| (echo "FAIL: search --help failed" && exit 1)

_test-wheel-contents:
	@echo "--- test: built wheel ships entrypoints and search_app"
	cd $(GENERATED_PROJECT) && rm -rf dist && uv build --wheel > /dev/null
	cd $(GENERATED_PROJECT) && unzip -l dist/*.whl \
		| grep -q "entrypoints/ingest.py" \
		&& unzip -l dist/*.whl | grep -q "search_app/__init__.py" \
		&& echo "OK: wheel contains entrypoints and search_app" \
		|| (echo "FAIL: wheel is missing required packages" && exit 1)
