"""Render the collection declaration to `alembic/structure.sql`.

A checked-in snapshot of the schema the running app expects, so a change to the declaration --
or to a search-toolkit upgrade that alters the chunk table -- shows up as a reviewable diff
instead of only inside a migration nobody reads. `tests/test_structure.py` fails when it is
stale.

This renders the *declaration*, so it needs neither Postgres nor `pg_dump` and runs anywhere.
It is one half of a pair:

- this file pins what the app binds to, diffable without a database
- `alembic check` in `tests/test_migrations.py` pins the chain against the declaration -- that
  the revisions actually build it, which does need a database

Regenerate with `make structure`.
"""

from pathlib import Path

from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from search_app import POSTGRES_COLLECTION

STRUCTURE_PATH = Path(__file__).resolve().parents[2] / "alembic" / "structure.sql"

_HEADER = """\
-- Generated by `make structure` from the collection declared in src/search_app/__init__.py.
-- Do not edit by hand: tests/test_structure.py fails when this file and the declaration differ.
--
-- This is the shape the running app expects. The Alembic chain in alembic/versions/ is what
-- builds it; `alembic check` is what proves the two agree.
"""


def render_structure() -> str:
    """The declaration's DDL, rendered for Postgres.

    Indexes are emitted in name order rather than declaration order, because `Table.indexes`
    is a set and an unsorted render would flap between runs. Trailing whitespace is stripped
    because SQLAlchemy's `CREATE TABLE` renderer emits it after every column, and an editor or
    hook that trims it would otherwise leave this file permanently failing its own test.
    """
    table = POSTGRES_COLLECTION.to_table(metadata=MetaData())
    dialect = postgresql.dialect()

    statements = [str(CreateTable(table).compile(dialect=dialect)).strip()]
    statements += [
        str(CreateIndex(index).compile(dialect=dialect)).strip()
        for index in sorted(table.indexes, key=lambda index: index.name or "")
    ]
    rendered = _HEADER + "\n" + "".join(f"{statement};\n\n" for statement in statements)
    return "\n".join(line.rstrip() for line in rendered.split("\n"))


def write_structure(path: Path = STRUCTURE_PATH) -> Path:
    path.write_text(render_structure())
    return path


if __name__ == "__main__":
    print(f"wrote {write_structure()}")
